- apt: name={{item.name}} state=present
  with_items:
  - { name: postgresql }
  - { name: postgresql-contrib }
- template:
    src: postgresql.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

