- yum: name={{ item.name }} state=present
  with_items:
  - { name: postgresql-server }
  - { name: postgresql-contrib }

- shell:
    postgresql-setup initdb
- template:
    src: postgresql.j2
    dest: /var/lib/pgsql/data/postgresql.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

